### ISSUE TITLE
Stories Tab Mockup and Requirements 

### ISSUE THREAD

**Issue by daliamaarek** [JSTech2020/group_d#1]
Acceptance Criteria: 
- [x] Requirements should be clearly written out and ready for implementation
- [x] Sketches should be clear enough to display each requirement

**Comment by klarmannsonia** [comment]
[Stories tab - requirements.pdf](https://github.com/JSTech2020/group_d/files/4368852/Stories.tab.-.requirements.pdf)
[Stories tab - mockups.pdf](https://github.com/JSTech2020/group_d/files/4368853/Stories.tab.-.mockups.pdf)

**Comment by klarmannsonia** [comment]
Online mockup editor: https://designer.gravit.io/?token=22LEZlWdFtiXdOHR0eZwk9xWkSFM7M4k
