### ISSUE TITLE
Project Database Mockup and Requirements

### ISSUE THREAD

**Issue by daliamaarek** [JSTech2020/group_d#2]
Acceptance Criteria: 
- [x] Requirements should be clearly written out and ready for implementation
- [x] Sketches should be clear enough to display each requirement

**Comment by ahmad-diaa** [comment]
Requirements File:
https://docs.google.com/document/d/1IBxUhKAYtR8ce92Cno80STfuMzUHCBe8__cwh4c0fwI/edit
